before_commands:
    - "composer update --prefer-source --ignore-platform-reqs"

checks:
    php:
        custom_coding_standard:
            ruleset_path: 'phpcs.xml'

tools:
    external_code_coverage:
        timeout: 1800
    php_code_coverage:
        enabled: true
    php_code_sniffer:
        enabled: true
    php_cpd:
        enabled: true
        excluded_dirs: ["test", "vendor"]
    php_cs_fixer:
        enabled: false
    php_loc:
        enabled: true
        excluded_dirs: ["test", "vendor"]
    php_mess_detector:
        enabled: true
        filter:
            paths: ["src/*"]
    php_pdepend:
        enabled: true
        excluded_dirs: ["test", "vendor"]
    php_analyzer:
        enabled: true
        filter:
            paths: ["src/*", "test/*"]
    sensiolabs_security_checker: true
