language: php

sudo: false
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/composer

php:
  - 7.0

before_install:
  - pecl install pthreads
  - pecl install -f msgpack
  - phpenv config-rm xdebug.ini

install:
  - composer install

script:
  - phpdbg -qrr vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - vendor/bin/phpcs

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
